### ISSUE TITLE
Importerror

### ISSUE THREAD

**Issue by oliver0922** [fundamentalvision/BEVFormer#181]
I followd the instructions for install but there's import error from mmcv
The problem is as follows

python3.8/site-packages/mmcv/_ext.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK2at10TensorBase8data_ptrIdEEPT_v

I installed mmcv-full==1.4.0 and all the version of packages are same with the recommendation.

**Comment by ashun989** [comment]
> I followd the instructions for install but there's import error from mmcv The problem is as follows
> 
> python3.8/site-packages/mmcv/_ext.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK2at10TensorBase8data_ptrIdEEPT_v
> 
> I installed mmcv-full==1.4.0 and all the version of packages are same with the recommendation.

I met the same problem, how did you finally solve it? @oliver0922

**Comment by ashun989** [comment]
> > I followd the instructions for install but there's import error from mmcv The problem is as follows
> > python3.8/site-packages/mmcv/_ext.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK2at10TensorBase8data_ptrIdEEPT_v
> > I installed mmcv-full==1.4.0 and all the version of packages are same with the recommendation.
> 
> I met the same problem, how did you finally solve it? @oliver0922

Problem was solved. It is caused by mismatch of cuda versions between mmcv and pytorch. My nvcc version is 11.7, so mmcv should be installed by precompiled wheel rather than compiled locally. In a nutsheel, the steps are:
1. `pip uinstall mmcv-full`
2. `pip cache remove mmcv-full*`
3. `pip install mmcv-full==1.4.0 -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.9.0/index.html`
4. `cd <PATH TO MMDET3D>` and `pip install -e . -v`

**Comment by wenyuqing** [comment]
> so: undefined symbol:

Hi, so after re-install mmcv-full, the mmdet3d need to be recompiled again? I meet the same problem and I have finished all install steps but get the bug when importing the dataset.
