### ISSUE TITLE
关于optimizer和img_backbone的设置问题～

### ISSUE THREAD

**Issue by pingyang97** [fundamentalvision/BEVFormer#218]
您好，关于optimizer的设置，您这边设置了 'img_backbone': dict(lr_mult=0.1)，请问这个有什么特殊的说法吗？

optimizer = dict(
type='AdamW',
lr=2e-4,
paramwise_cfg=dict(
custom_keys={
'img_backbone': dict(lr_mult=0.1),
}),
weight_decay=0.01)

在img_backbone这边，为什么选择frozen_stages=1呢？
img_backbone=dict(
type='ResNet',
depth=101,
num_stages=4,
out_indices=(1,2,3),
frozen_stages=1,
norm_cfg=dict(type='BN2d', requires_grad=False),
norm_eval=True,
style='caffe',
#with_cp=True, # using checkpoint to save GPU memory
dcn=dict(type='DCNv2', deform_groups=1, fallback_on_stride=False), # original DCNv2 will print log when perform load_state_dict
stage_with_dcn=(False, False, True, True)),

非常感谢您的阅读，期待能够尽快得到您会回复～

**Comment by htian01** [comment]
lr_mult=0.1 for 0.1x learining rate for image backbone , since I have already been pretrained and training steability.
For frozen_stages=1, its a common trick for training such pretrained image backbone, since too show feature is no need for training and save the computation. You can also set it to -1 for unfreeze all image backbone, it may slight improve the performance.
